[package]
name = "hello"
version = "1.1.0"
authors = ["Chris Guest <chris.guest75@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
